export function defineLeetCodeThemes(monaco) {
  monaco.editor.defineTheme("leetcode-dark", {
    base: "vs-dark",
    inherit: true,
    rules: [
      { token: "keyword", foreground: "d2a8ff" },
      { token: "storage", foreground: "d2a8ff" },
      { token: "modifier", foreground: "d2a8ff" },
      { token: "type", foreground: "79c0ff" },
      { token: "string", foreground: "a5d6ff" },
      { token: "comment", foreground: "8b949e" },
      { token: "number", foreground: "79c0ff" },
      { token: "constant", foreground: "79c0ff" },
      { token: "identifier", foreground: "e6edf3" },
      { token: "delimiter", foreground: "8b949e" },
      { token: "operator", foreground: "e6edf3" },
      { token: "tag", foreground: "7ee787" },
      { token: "attribute.name", foreground: "79c0ff" },
      { token: "attribute.value", foreground: "a5d6ff" },
    ],
    colors: {
      "editor.background": "#1a1a1a",
      "editor.foreground": "#e6edf3",
      "editorLineNumber.foreground": "#6e7681",
      "editorLineNumber.activeForeground": "#e6edf3",
      "editor.lineHighlightBackground": "#262626",
      "editorCursor.foreground": "#e6edf3",
      "editor.selectionBackground": "#264f78",
      "editor.inactiveSelectionBackground": "#1c2b3a",
      "editorIndentGuide.background1": "#2e2e2e",
      "editorIndentGuide.activeBackground1": "#4a4a4a",
      "editorWidget.background": "#1f1f1f",
      "editorSuggestWidget.background": "#1f1f1f",
      "editorHoverWidget.background": "#1f1f1f",
      "scrollbarSlider.background": "#4a4a4a80",
      "scrollbarSlider.hoverBackground": "#5a5a5a80",
      "editorGutter.background": "#1a1a1a",
    },
  });
  monaco.editor.defineTheme("leetcode-light", {
    base: "vs",
    inherit: true,
    rules: [
      { token: "keyword", foreground: "6f42c1" },
      { token: "storage", foreground: "6f42c1" },
      { token: "modifier", foreground: "6f42c1" },
      { token: "type", foreground: "2b6cb0" },
      { token: "string", foreground: "0a3069" },
      { token: "comment", foreground: "1a7f37" },
      { token: "number", foreground: "0550ae" },
      { token: "constant", foreground: "0550ae" },
      { token: "identifier", foreground: "24292f" },
      { token: "delimiter", foreground: "6e7781" },
      { token: "operator", foreground: "24292f" },
      { token: "tag", foreground: "116329" },
      { token: "attribute.name", foreground: "0550ae" },
      { token: "attribute.value", foreground: "0a3069" },
    ],
    colors: {
      "editor.background": "#ffffff",
      "editor.foreground": "#24292f",
      "editorLineNumber.foreground": "#8c959f",
      "editorLineNumber.activeForeground": "#24292f",
      "editor.lineHighlightBackground": "#f6f8fa",
      "editorCursor.foreground": "#24292f",
      "editor.selectionBackground": "#b6d7ff",
      "editorIndentGuide.background1": "#e5e7eb",
      "editorIndentGuide.activeBackground1": "#c9cdd3",
      "editorWidget.background": "#ffffff",
      "scrollbarSlider.background": "#8c959f66",
      "editorGutter.background": "#ffffff",
    },
  });
}
